TEXTS = {
    "uz": {
        "welcome": "👋 Salom, {name}!\n\n🤖 Men <b>KibrliyBolaBot</b>man!\n\nQuyidagi bo'limlardan birini tanlang:",
        "welcome_group": "🎉 Guruhimizga xush kelibsiz, {name}!\n\nQoidalar bilan tanishing va samarali muloqot qiling. 📚",
        "main_menu": "🏠 <b>Asosiy Menyu</b>\n\nBo'lim tanlang:",
        "games_menu": "🎮 <b>O'yinlar Bo'limi</b>\n\nO'yin tanlang:",
        "fun_menu": "😄 <b>Qiziqarli Bo'lim</b>\n\nNimani xohlaysiz?",
        "translator_help": "🌐 <b>Tarjimon</b>\n\nFormat: <code>uz-en Salom dunyo</code>\n\nMavjud tillar:\n🇺🇿 uz | 🇷🇺 ru | 🇬🇧 en | 🇸🇦 ar\n🇹🇷 tr | 🇫🇷 fr | 🇩🇪 de | 🇰🇷 ko\n🇨🇳 zh | 🇯🇵 ja | 🇮🇹 it | 🇪🇸 es",
        "bonus_received": "🎁 Tabriklaymiz! Bugungi bonusingiz: <b>+{points} ball</b>\n\n💰 Jami ballingiz: <b>{total}</b>",
        "bonus_already": "⏳ Bugun allaqachon bonus oldingiz!\n\nKeyingi bonus: <b>{time}</b> dan keyin",
        "warn_message": "⚠️ <b>Ogohlantirish!</b>\n\n{user}, guruh qoidalarini buzdingiz!\nOgohlantirishlar: <b>{warns}/3</b>\n\n3 ta ogohlantirish = BAN ❌",
        "muted": "🔇 {user} 10 daqiqaga o'qish rejimiga o'tkazildi.",
        "banned": "🚫 {user} guruhdan chiqarildi! (3 ta ogohlantirish)",
        "tanishish_warning": "👋 {user}\n\n❌ Bu guruh tanishish uchun emas!\nIltimos, boshqa joylarda tanishing.\n\nXabaringiz o'chirildi. ⚠️",
        "spam_warning": "📵 {user}, juda ko'p xabar yozdingiz!\nBir oz kuting...",
        "admin_msg_received": "✅ Xabaringiz adminga yuborildi!\nAdmin tez orada javob beradi. 🕐",
        "ticket_created": "🎫 <b>Ticket #{ticket_id}</b>\n\n📩 Yangi xabar!\n👤 Foydalanuvchi: {name}\n🆔 ID: <code>{user_id}</code>\n📱 Username: @{username}\n🕐 Vaqt: {time}\n\n💬 Xabar:\n{text}",
        "reply_sent": "✅ Admin javob berdi:\n\n{reply}",
        "quiz_alert": "📢 <b>Diqqat Adminlar!</b>\n\n🔔 QuizBot to'xtab qoldi yoki test tugadi!\nIltimos yangi test tashlang.",
        "no_quiz_long": "⚠️ <b>Adminlar!</b> Uzoq vaqtdan beri test yo'q. Yangi test tashlashni unutmang!",
        "contact_admin": "📩 <b>Adminga Xabar</b>\n\nXabaringizni yozing, admin tez orada javob beradi:",
        "score_info": "💰 <b>Ballaringiz</b>\n\n👤 {name}\n🏆 Jami ball: <b>{score}</b>",
        "help_text": "ℹ️ <b>Yordam</b>\n\nBu bot ingliz tili guruhini boshqarish uchun yaratilgan.\n\n📌 Asosiy imkoniyatlar:\n• Guruh himoyasi\n• O'yinlar\n• Tarjimon\n• Kunlik bonus\n• Admin bilan bog'lanish",
        "admin_panel": "⚙️ <b>Admin Panel</b>\n\nBo'lim tanlang:",
        "lang_changed": "✅ Bot tili o'zbekchaga o'zgartirildi!",
        "broadcast_prompt": "📢 Barcha foydalanuvchilarga yuboriladigan xabarni yozing:",
        "broadcast_done": "✅ Xabar {count} foydalanuvchiga yuborildi!",
        "stats_text": "📊 <b>Statistika</b>\n\n👥 Jami foydalanuvchilar: {users}\n💬 Jami xabarlar: {messages}\n🎮 O'yinlar o'ynalgan: {games}",
        "mandatory_on": "✅ Majburiy a'zolik yoqildi!",
        "mandatory_off": "❌ Majburiy a'zolik o'chirildi!",
        "must_join": "⚠️ Botdan foydalanish uchun quyidagi kanal/guruhlarga a'zo bo'ling:",
        "user_not_found": "❌ Foydalanuvchi topilmadi!",
        "action_done": "✅ Amal bajarildi!",
        "back": "◀️ Orqaga",
        "close": "❌ Yopish",
        "loading": "⏳ Yuklanmoqda...",
    },
    "ru": {
        "welcome": "👋 Привет, {name}!\n\n🤖 Я <b>KibrliyBolaBot</b>!\n\nВыберите раздел:",
        "welcome_group": "🎉 Добро пожаловать в группу, {name}!\n\nОзнакомьтесь с правилами! 📚",
        "main_menu": "🏠 <b>Главное Меню</b>\n\nВыберите раздел:",
        "games_menu": "🎮 <b>Игры</b>\n\nВыберите игру:",
        "fun_menu": "😄 <b>Развлечения</b>\n\nЧто хотите?",
        "translator_help": "🌐 <b>Переводчик</b>\n\nФормат: <code>ru-en Привет мир</code>",
        "bonus_received": "🎁 Поздравляем! Ваш бонус: <b>+{points} очков</b>\n\n💰 Всего очков: <b>{total}</b>",
        "bonus_already": "⏳ Вы уже получили бонус сегодня!\n\nСледующий бонус через: <b>{time}</b>",
        "warn_message": "⚠️ <b>Предупреждение!</b>\n\n{user}, вы нарушили правила!\nПредупреждения: <b>{warns}/3</b>",
        "muted": "🔇 {user} переведён в режим чтения на 10 минут.",
        "banned": "🚫 {user} исключён из группы! (3 предупреждения)",
        "tanishish_warning": "👋 {user}\n\n❌ Это не группа для знакомств!\nПожалуйста, знакомьтесь в других местах.\n\nСообщение удалено. ⚠️",
        "spam_warning": "📵 {user}, вы пишете слишком много!\nПодождите немного...",
        "admin_msg_received": "✅ Ваше сообщение отправлено администратору!\nОн ответит в ближайшее время. 🕐",
        "ticket_created": "🎫 <b>Тикет #{ticket_id}</b>\n\n📩 Новое сообщение!\n👤 Пользователь: {name}\n🆔 ID: <code>{user_id}</code>\n📱 Username: @{username}\n🕐 Время: {time}\n\n💬 Сообщение:\n{text}",
        "reply_sent": "✅ Администратор ответил:\n\n{reply}",
        "quiz_alert": "📢 <b>Внимание Администраторы!</b>\n\n🔔 QuizBot остановился или тест завершён!\nПожалуйста, отправьте новый тест.",
        "no_quiz_long": "⚠️ <b>Администраторы!</b> Долго нет теста. Не забудьте отправить новый!",
        "contact_admin": "📩 <b>Написать Администратору</b>\n\nНапишите ваше сообщение:",
        "score_info": "💰 <b>Ваши Очки</b>\n\n👤 {name}\n🏆 Всего: <b>{score}</b>",
        "help_text": "ℹ️ <b>Помощь</b>\n\nБот для управления группой английского языка.",
        "admin_panel": "⚙️ <b>Панель Администратора</b>\n\nВыберите раздел:",
        "lang_changed": "✅ Язык бота изменён на русский!",
        "broadcast_prompt": "📢 Напишите сообщение для всех пользователей:",
        "broadcast_done": "✅ Сообщение отправлено {count} пользователям!",
        "stats_text": "📊 <b>Статистика</b>\n\n👥 Всего пользователей: {users}\n💬 Всего сообщений: {messages}\n🎮 Игр сыграно: {games}",
        "mandatory_on": "✅ Обязательная подписка включена!",
        "mandatory_off": "❌ Обязательная подписка отключена!",
        "must_join": "⚠️ Для использования бота подпишитесь на:",
        "user_not_found": "❌ Пользователь не найден!",
        "action_done": "✅ Действие выполнено!",
        "back": "◀️ Назад",
        "close": "❌ Закрыть",
        "loading": "⏳ Загрузка...",
    },
    "en": {
        "welcome": "👋 Hello, {name}!\n\n🤖 I'm <b>KibrliyBolaBot</b>!\n\nChoose a section:",
        "welcome_group": "🎉 Welcome to the group, {name}!\n\nPlease read the rules! 📚",
        "main_menu": "🏠 <b>Main Menu</b>\n\nChoose a section:",
        "games_menu": "🎮 <b>Games Section</b>\n\nChoose a game:",
        "fun_menu": "😄 <b>Fun Section</b>\n\nWhat do you want?",
        "translator_help": "🌐 <b>Translator</b>\n\nFormat: <code>en-uz Hello world</code>",
        "bonus_received": "🎁 Congratulations! Your daily bonus: <b>+{points} points</b>\n\n💰 Total points: <b>{total}</b>",
        "bonus_already": "⏳ You already claimed your bonus today!\n\nNext bonus available in: <b>{time}</b>",
        "warn_message": "⚠️ <b>Warning!</b>\n\n{user}, you violated group rules!\nWarnings: <b>{warns}/3</b>",
        "muted": "🔇 {user} has been muted for 10 minutes.",
        "banned": "🚫 {user} has been banned! (3 warnings)",
        "tanishish_warning": "👋 {user}\n\n❌ This is not a dating group!\nPlease meet people elsewhere.\n\nYour message was deleted. ⚠️",
        "spam_warning": "📵 {user}, you are sending too many messages!\nPlease slow down...",
        "admin_msg_received": "✅ Your message has been sent to admin!\nThey will reply soon. 🕐",
        "ticket_created": "🎫 <b>Ticket #{ticket_id}</b>\n\n📩 New Message!\n👤 User: {name}\n🆔 ID: <code>{user_id}</code>\n📱 Username: @{username}\n🕐 Time: {time}\n\n💬 Message:\n{text}",
        "reply_sent": "✅ Admin replied:\n\n{reply}",
        "quiz_alert": "📢 <b>Attention Admins!</b>\n\n🔔 QuizBot stopped or test is done!\nPlease send a new test.",
        "no_quiz_long": "⚠️ <b>Admins!</b> No test for a long time. Don't forget to send a new one!",
        "contact_admin": "📩 <b>Contact Admin</b>\n\nWrite your message, admin will reply soon:",
        "score_info": "💰 <b>Your Score</b>\n\n👤 {name}\n🏆 Total: <b>{score}</b>",
        "help_text": "ℹ️ <b>Help</b>\n\nBot for managing English language group.",
        "admin_panel": "⚙️ <b>Admin Panel</b>\n\nChoose section:",
        "lang_changed": "✅ Bot language changed to English!",
        "broadcast_prompt": "📢 Write a message to send to all users:",
        "broadcast_done": "✅ Message sent to {count} users!",
        "stats_text": "📊 <b>Statistics</b>\n\n👥 Total users: {users}\n💬 Total messages: {messages}\n🎮 Games played: {games}",
        "mandatory_on": "✅ Mandatory subscription enabled!",
        "mandatory_off": "❌ Mandatory subscription disabled!",
        "must_join": "⚠️ To use the bot, join these channels/groups:",
        "user_not_found": "❌ User not found!",
        "action_done": "✅ Action completed!",
        "back": "◀️ Back",
        "close": "❌ Close",
        "loading": "⏳ Loading...",
    }
}

def t(key, lang=None, **kwargs):
    from utils import db
    if lang is None:
        lang = db.get_bot_lang()
    text = TEXTS.get(lang, TEXTS["uz"]).get(key, TEXTS["uz"].get(key, key))
    if kwargs:
        try:
            text = text.format(**kwargs)
        except:
            pass
    return text
